# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

countries: [BN, KH, ID, LA, MY, MM, PH, SG, TH, VN]
# Can be replaced by country ["NG", "BJ"], continent ["Africa"] or user-specific region, see more at https://pypsa-earth.readthedocs.io/en/latest/configuration.html#top-level-configuration

subregion: # remove 'false' if subregion are to be specified
  define_by_gadm:
    Java-Bali/ID:
      ID: [2,4,7,9,10,11,33]
    Peninsular/MY:
      MY: [1,2,3,4,6,7,8,9,10,11,12,15,16]
    Papua/ID:
      ID: [22,23]
    Sarawak/MY:
      MY: [14]
    Maluku/ID:
      ID: [18,19]
    Sulawesi/ID:
      ID: [6,25,26,27,28,29]
    Sabah/MY:
      MY: [5,13]
    Kalimantan/ID:
      ID: [12,13,14,34,35]
    Nusa-Tenggara/ID:
      ID: [20,21]
    Sumatra/ID:
      ID: [1,3,5,8,16,17,24,30,31,32]

enable:
  retrieve_databundle: false #  Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: false
  retrieve_cost_data: false # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: false # If 'true', OpenStreetMap data will be downloaded for the above given countries
  build_natura_raster: false # If True, then an exclusion raster will be build
  build_cutout: false

cluster_options:
  simplify_network:
    remove_stubs: false
    remove_stubs_across_borders: false
    p_threshold_drop_isolated: 0 # [MW] isolated buses are being discarded if bus mean power is below the specified threshold
    p_threshold_merge_isolated: 30 # [MW] isolated buses are being merged into a single isolated bus if a bus mean power is below the specified threshold
    s_threshold_fetch_isolated: 0.1 # [-] a share of the national load for merging an isolated network into a backbone network